set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} /D_SECURE_SCL=0")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} /D_SECURE_SCL=0")

set(VCPKG_PLATFORM_TOOLSET v143)